name: DenisTek Site Monitor

on:
  schedule:
    # Run every 2 hours (0 */2 * * *)
    - cron: '0 */2 * * *'
  workflow_dispatch:
    inputs:
      website_urls:
        description: 'Website URLs to test (comma-separated, optional, defaults to environment variable)'
        required: false
        type: string

jobs:
  chatbot-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Playwright
        run: |
          npm install playwright@1.54.2
          npx playwright install chromium
          
      - name: Run chatbot test
        env:
          WEBSITE_URL: ${{ inputs.website_urls || secrets.APP_WEBSITE_URLS || secrets.APP_WEBSITE_URL || 'https://denistek.online' }}
        run: |
          node .github/scripts/denistek-site-playwright-test.js
          
      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: chatbot-test-screenshots-${{ github.run_id }}
          path: |
            *.png
          retention-days: 7
          
      - name: Upload screenshots on success
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: chatbot-success-screenshots-${{ github.run_id }}
          path: |
            *final*.png
          retention-days: 3
          
      - name: Send Slack notification on success
        if: success()
        run: |
          # Get the website URLs and count them
          WEBSITE_URLS="${{ inputs.website_urls || secrets.APP_WEBSITE_URLS || secrets.APP_WEBSITE_URL || 'https://denistek.online' }}"
          WEBSITE_COUNT=$(echo "$WEBSITE_URLS" | tr ',' '\n' | wc -l)
          
          # Create website list for Slack message
          WEBSITE_LIST=""
          IFS=',' read -ra URLS <<< "$WEBSITE_URLS"
          for url in "${URLS[@]}"; do
            url=$(echo "$url" | xargs)  # trim whitespace
            WEBSITE_LIST="$WEBSITE_LIST<$url|$url>\n"
          done
          
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":robot_face: *DenisTek Chatbot Test Successful*\n\nPlaywright chatbot test completed successfully on '"$WEBSITE_COUNT"' website(s)! Greg Lam AI is responding properly."
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Websites Tested:*\n'"$WEBSITE_LIST"'"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Test Email:*\nplaywright@test.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Time:*\n<!date^'"$(date +%s)"'^{date_short_pretty} {time}|'"$(date)"'>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Status:*\nAll chatbots responding normally"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Workflow"
                    },
                    "url": "'"$GITHUB_SERVER_URL"'/'"$GITHUB_REPOSITORY"'/actions/runs/'"$GITHUB_RUN_ID"'"
                  }
                ]
              }
            ]
          }' \
          '${{ secrets.SLACK_WEBHOOK_URL_FOR_MONITORING }}'
          
      - name: Send Slack notification on failure
        if: failure()
        run: |
          # Get the website URLs and count them
          WEBSITE_URLS="${{ inputs.website_urls || secrets.APP_WEBSITE_URLS || secrets.APP_WEBSITE_URL || 'https://denistek.online' }}"
          WEBSITE_COUNT=$(echo "$WEBSITE_URLS" | tr ',' '\n' | wc -l)
          
          # Create website list for Slack message
          WEBSITE_LIST=""
          IFS=',' read -ra URLS <<< "$WEBSITE_URLS"
          for url in "${URLS[@]}"; do
            url=$(echo "$url" | xargs)  # trim whitespace
            WEBSITE_LIST="$WEBSITE_LIST<$url|$url>\n"
          done
          
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":warning: *DenisTek Chatbot Test Failed*\n\nPlaywright chatbot test encountered an error on one or more websites! Greg Lam AI may not be responding properly."
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Websites Tested:*\n'"$WEBSITE_LIST"'"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Test Email:*\nplaywright@test.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Time:*\n<!date^'"$(date +%s)"'^{date_short_pretty} {time}|'"$(date)"'>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Status:*\nOne or more chatbot tests failed"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Workflow"
                    },
                    "url": "'"$GITHUB_SERVER_URL"'/'"$GITHUB_REPOSITORY"'/actions/runs/'"$GITHUB_RUN_ID"'"
                  }
                ]
              }
            ]
          }' \
          '${{ secrets.SLACK_WEBHOOK_URL_FOR_MONITORING }}'
