name: DenisTek Site Monitor

on:
  schedule:
    # Run every 2 hours (0 */2 * * *)
    - cron: '0 */2 * * *'
  workflow_dispatch:
    inputs:
      website_url:
        description: 'Website URL to test (optional, defaults to environment variable)'
        required: false
        type: string

jobs:
  chatbot-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Playwright
        run: |
          npm install playwright@1.54.2
          npx playwright install chromium
          
      - name: Run chatbot test
        env:
          WEBSITE_URL: ${{ inputs.website_url || secrets.APP_WEBSITE_URL || 'https://denistek.online/' }}
        run: |
          node .github/scripts/denistek-site-playwright-test.js
          
      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: chatbot-test-screenshots-${{ github.run_id }}
          path: |
            *.png
          retention-days: 7
          
      - name: Upload screenshots on success
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: chatbot-success-screenshots-${{ github.run_id }}
          path: |
            chatbot-test-final.png
          retention-days: 3
          
      - name: Send Slack notification on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":robot_face: *DenisTek Chatbot Test Successful*\n\nPlaywright chatbot test completed successfully! Greg Lam AI is responding properly."
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Website:*\n<'"$WEBSITE_URL"'|'"$WEBSITE_URL"'>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Test Email:*\nplaywright@test.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Time:*\n<!date^'"$(date +%s)"'^{date_short_pretty} {time}|'"$(date)"'>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Status:*\nChatbot responding normally"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Workflow"
                    },
                    "url": "'"$GITHUB_SERVER_URL"'/'"$GITHUB_REPOSITORY"'/actions/runs/'"$GITHUB_RUN_ID"'"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Test Chatbot"
                    },
                    "url": "'"$WEBSITE_URL"'/p/greg"
                  }
                ]
              }
            ]
          }' \
          '${{ secrets.SLACK_WEBHOOK_URL_FOR_MONITORING }}'
        env:
          WEBSITE_URL: ${{ inputs.website_url || secrets.WEBSITE_URL || 'https://denistek.online/' }}
          
      - name: Send Slack notification on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":warning: *DenisTek Chatbot Test Failed*\n\nPlaywright chatbot test encountered an error! Greg Lam AI may not be responding properly."
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Website:*\n<'"$WEBSITE_URL"'|'"$WEBSITE_URL"'>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Test Email:*\nplaywright@test.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Time:*\n<!date^'"$(date +%s)"'^{date_short_pretty} {time}|'"$(date)"'>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Status:*\nChatbot test failed"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Workflow"
                    },
                    "url": "'"$GITHUB_SERVER_URL"'/'"$GITHUB_REPOSITORY"'/actions/runs/'"$GITHUB_RUN_ID"'"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Check Website"
                    },
                    "url": "'"$WEBSITE_URL"'"
                  }
                ]
              }
            ]
          }' \
          '${{ secrets.SLACK_WEBHOOK_URL_FOR_MONITORING }}'
        env:
          WEBSITE_URL: ${{ inputs.website_url || secrets.WEBSITE_URL || 'https://denistek.online/' }}
